aws_dbt_snowflake_project:
  outputs:
    dev:
      account: ********* #snowflake account
      database: AIRBNB
      password: ******** #snowflake account password
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: arbazmd
      warehouse: COMPUTE_WH
  target: dev
